### ISSUE TITLE
Simplify abstract parser class

### ISSUE THREAD

**Issue by everyonesdesign** [everyonesdesign/enru#8]
It's possible to change AbstractParser code to something like this:

``` python
class BaseParser:
    def get_url(self):
        raise NotImplementedException()

    def get_content(self):
        raise NotImplementedException()
```

On one hand the code becomes much more simpler.
On the other, it seems that this code cares about number of passed arguments to not implemented method. Not sure if it's expected behavior actually.

**Comment by despawnerer** [comment]
Isn't the abstract class supposed to specify the function args anyway? What you're doing with it is basically specifying the common interface between different parsers, so it's a good idea to be explicit about the methods' args. The documentation for the `NotImplementedError` exception actually codifies this usage, sort of: https://docs.python.org/2/library/exceptions.html#exceptions.NotImplementedError
